### ISSUE TITLE
Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by mfonsen** [takomo-io/takomo#110] opened 2020-10-09 11:20 UTC
After adding one more stack to an application with ~25 stacks I got the following error in deployment summary:

`/foo/eu-west-1/bar/bar.yml/eu-west-1                      bar-eu-west-1-dev            FAILED     DEPENDENCIES_FAILED  50.5s     Cannot read property 'success' of undefined`

That new stack had one new dependency. This was resolved by removing the only dependency from that new stack. 

Also if only that new stack is deployed even with dependencies there are no problems. Or if the target of the dependency is deployed with dependencies.

The detailed error:
```
2020-10-09 17:17:59 +0300 [error] - /foo/eu-west-1/bar/bar.yml/eu-west-1 - An error occurred while waiting dependencies to complete TypeError: Cannot read property 'success' of undefined
    at /packages/takomo/1.5.1/node_modules/@takomo/stacks-commands/dist/stacks/deploy/wait.js:13:75
    at Array.find (<anonymous>)
    at Object.exports.waitForDependenciesToComplete (/packages/takomo/1.5.1/node_modules/@takomo/stacks-commands/dist/stacks/deploy/wait.js:13:60)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It seems that the array of dependencies contains one item that is undefined. The wait code assumes each is an object.

Takomo version 1.5.1. Installed with [Volta](https://docs.volta.sh/reference/install) install

This error was originally reported for 2.8.0. I also tested this with 2.8.0 but was not able to get the application working even without the new stack. But the error was the same and maybe might be related to swallowing of an error somewhere else. It might be related to Takomo using different Node version compared to the application.

**Comment by mfonsen** [comment] 2020-10-09 14:52
Edited the issue after finding a workaround for 1.5.1. On 2.8.0 there might be some other issue too so I only mention it separately.

**Comment by hmeltaus** [comment] 2020-10-09 17:22
Some additional questions:

- Did you run deploy with or without the `-y` or `--yes` option?
- Are you using parameter resolvers in your stacks?

**Comment by mfonsen** [comment] 2020-10-09 17:26
With ‘-y’. Parameter resolvers are in use. So are command and custom hooks.

**Comment by hmeltaus** [comment] 2020-10-09 19:30
I just released version `2.9.0`. There's now some more logging in place that hopefully helps to reveal the root cause of the issue. Once you have time, please try again with the `2.9.0` version and `--log trace`.

**Comment by mfonsen** [comment] 2020-10-10 06:17
Thank you. I tried the new 2.9.0. This stack configuration works with 1.5.1.

I noticed there's a new logging for stack deployment order. That shows that all stacks that fail due to reported error are in the list before their dependencies. There's one stack that fails due to it's dependencies failing. Please find the complete list below with notes. Stack names have been changed.

```  - /foo/eu-north-1/a/a.yml/eu-north-1 
  - /foo/eu-west-1/b/b.yml/eu-west-1 
  - /foo/eu-west-1/c/c.yml/eu-west-1
  - /foo/eu-west-1/a/a.yml/eu-west-1
  - /foo/eu-west-1/d/d.yml/eu-west-1
  - /foo/us-east-1/b/b.yml/us-east-1
  - /foo/us-east-1/x/x.yml/us-east-1
  - /foo/eu-north-1/e/e.yml/eu-north-1 -- eu-north-1/a/a.yml
  - /foo/eu-west-1/f/f.yml/eu-west-1 -- eu-west-1/p/p.yml (NOTE: dependency below) FAILED Cannot read property 'success' of undefined
  - /foo/eu-west-1/g/g.yml/eu-west-1 --> us-east-1/x/x.yml
  - /foo/eu-west-1/h/h.yml/eu-west-1 -->   - us-east-1/x/x.yml, eu-west-1/g/g.yml
  - /foo/eu-west-1/i/i.yml/eu-west-1 -->   - us-east-1/x/x.yml, eu-west-1/g/g.yml
  - /foo/eu-west-1/j/j.yml/eu-west-1 -->   - eu-west-1/h/h.yml, eu-west-1/p/p.yml, us-east-1/t/t.yml, eu-west-1/r/r.yml, eu-west-1/q/q.yml (NOTE: dependency below) FAILED Cannot read property 'success' of undefined
  - /foo/eu-west-1/k/k.yml/eu-west-1 -->   - eu-west-1/p/p.yml, eu-west-1/h/h.yml, eu-west-1/i/i.yml, eu-west-1/q/q.yml (NOTE: dependency below) FAILED Cannot read property 'success' of undefined
  - /foo/eu-west-1/l/l.yml/eu-west-1 -->  - eu-west-1/p/p.yml, eu-west-1/h/h.yml, eu-west-1/q/q.yml (NOTE: dependency below) FAILED Cannot read property 'success' of undefined
  - /foo/eu-west-1/m/m.yml/eu-west-1 -->   - eu-west-1/p/p.yml, us-east-1/t/t.yml, eu-west-1/i/i.yml, eu-west-1/h/h.yml, eu-west-1/a/a.yml, eu-west-1/r/r.yml, eu-west-1/q/q.yml (NOTE: dependency below) FAILED Dependencies failed
  - /foo/eu-west-1/n/n.yml/eu-west-1 -->    - eu-west-1/p/p.yml, us-east-1/t/t.yml, eu-west-1/i/i.yml, eu-west-1/h/h.yml, eu-west-1/a/a.yml, eu-west-1/r/r.yml, eu-west-1/q/q.yml (NOTE: dependency below) FAILED Cannot read property 'success' of undefined
  - /foo/eu-west-1/o/o.yml/eu-west-1 -->   - eu-west-1/c/c.yml, eu-west-1/h/h.yml
  - /foo/us-east-1/g/g.yml/us-east-1 --> us-east-1/x/x.yml
  - /foo/eu-west-1/p/p.yml/eu-west-1 -->   - us-east-1/g/g.yml
  - /foo/eu-west-1/q/q.yml/eu-west-1 -->   - eu-west-1/p/p.yml, eu-west-1/h/h.yml
  - /foo/eu-west-1/r/r.yml/eu-west-1 --> eu-west-1/p/p.yml, eu-west-1/h/h.yml
  - /foo/eu-west-1/s/s.yml/eu-west-1 -->   - eu-west-1/p/p.yml, eu-west-1/c/c.yml, eu-west-1/h/h.yml, eu-west-1/r/r.yml, eu-west-1/q/q.yml
  - /foo/us-east-1/t/t.yml/us-east-1 -->   - eu-west-1/p/p.yml,  - eu-west-1/c/c.yml
```

If I leave the `-y` out and choose to review each stack manually I got the following error:

```
2020-10-10 08:06:37 +0300 [debug] - /events/eu-north-1/a/a.yml - Change set creation failed with reason: No updates are to be performed.
2020-10-10 08:06:37 +0300 [error] - /events/eu-north-1/a/a.yml/eu-north-1 - Failed to create change set Error: No updates are to be performed.
    at CloudFormationClient.waitUntilChangeSetIsReady (/packages/takomo/2.9.0/node_modules/@takomo/aws-clients/dist/cloudformation.js:173:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.exports.reviewChanges (/packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/review.js:54:27)
    at async Object.exports.prepareCloudFormationTemplate (/packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/template.js:121:20)
    at async Object.exports.executeDeployContext (/packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/execute-deploy-context.js:84:27)
    at async Object.exports.handle (/packages/takomo/2.9.0/node_modules/@takomo/cli/dist/common.js:243:24)

Stack path                                                     Stack name                        Status     Reason                    Time  Message                        
-------------------------------------------------------------  --------------------------------  ---------  ------------------------  ----  -------------------------------
/events/eu-north-1/a/a.yml/eu-north-1    a-eu-north-1-de   FAILED     CREATE_CHANGE_SET_FAILED  6.9s  No updates are to be performed.
/events/eu-west-1/b/b.yml/eu-west-1                          b-eu-west-1-devmika              CANCELLED  CANCELLED                 0ms   Cancelled                      
```

Just for reference, the TypeError on 2.9.0 is:
```
2020-10-10 08:08:09 +0300 [error] - /events/eu-west-1/n/n.yml/eu-west-1 - An error occurred while waiting dependencies to complete TypeError: Cannot read property 'success' of undefined
    at /packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/wait.js:13:75
    at Array.find (<anonymous>)
    at Object.exports.waitForDependenciesToComplete (/packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/wait.js:13:60)
    at async Promise.all (index 16)
    at async executeStacksInParallel (/packages/takomo/2.9.0/node_modules/@takomo/stacks-commands/dist/stacks/deploy/execute-deploy-context.js:32:21)
    at async Object.exports.handle (/packages/takomo/2.9.0/node_modules/@takomo/cli/dist/common.js:243:24)
```

Would there be something of interest in the logs?

I could try to create a simplified version of the stack that I could share. It would take some time.

Maybe there could be some logging where the list of dependencies is updated to catch the writer of `undefined`?

It might be a fun and useful feature to get the dependency graph out in visual format such as https://en.wikipedia.org/wiki/DOT_(graph_description_language)

Unfortunately I have limited access to the project in the following days, so it will take some time before I can try to work on this.

**Comment by mfonsen** [comment] 2020-10-10 06:48
Here are all the lines with the new "Dependency in stack does not exists" errors from the log. All the stack names have been changed manually so there could be errors here and in earlier comment.

```
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/p/p.yml/eu-west-1' in stack /events/eu-west-1/f/f.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/p/p.yml/eu-west-1' in stack /events/eu-west-1/j/j.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/us-east-1/t/t.yml/us-east-1' in stack /events/eu-west-1/j/j.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/r/r.yml/eu-west-1' in stack /events/eu-west-1/j/j.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/q/q.yml/eu-west-1' in stack /events/eu-west-1/j/j.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/p/p.yml/eu-west-1' in stack /events/eu-west-1/k/k.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/q/q.yml/eu-west-1' in stack /events/eu-west-1/k/k.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/p/p.yml/eu-west-1' in stack /events/eu-west-1/l/l.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/q/q.yml/eu-west-1' in stack /events/eu-west-1/l/l.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/p/p.yml/eu-west-1' in stack /events/eu-west-1/n/n.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/us-east-1/t/t.yml/us-east-1' in stack /events/eu-west-1/n/n.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/r/r.yml/eu-west-1' in stack /events/eu-west-1/n/n.yml/eu-west-1 does not exists
2020-10-10 08:07:10 +0300 [error] - Dependency '/events/eu-west-1/q/q.yml/eu-west-1' in stack /events/eu-west-1/n/n.yml/eu-west-1 does not exists
```

**Comment by hmeltaus** [comment] 2020-10-12 05:25
The error that you got in version 2.9.0 when reviewing the stack was fixed in #112 and included in version 2.10.0. Stacks with SAM transformations produce different message when there is no changes to perform and this was not handled properly. I don't think that this fixes the problem you have with dependencies, though. I'll continue to investigate the issue.

2.10.0 also has a new CLI command to print stacks dependency graph in DOT format. You need to paste the output to some tool that can draw the graph, e.g. https://dreampuf.github.io/GraphvizOnline

**Comment by mfonsen** [comment] 2020-10-12 07:06
Thank you very much.

Now when running without `-y` and by choosing to review each stack individually I get the same error as with `-y`

Here's the dependency graph output. The letters are most likely different than in earlier snippet:

```
{
  "/h/eu-north-1/a/a.yml/eu-north-1" -> "/h/eu-north-1/b/b.yml/eu-north-1"
  "/h/eu-north-1/b/b.yml/eu-north-1"
  "/h/eu-west-1/c/c.yml/eu-west-1" -> "/h/us-east-1/h/h.yml/us-east-1"
  "/h/eu-west-1/c/c.yml/eu-west-1" -> "/h/eu-west-1/s/s.yml/eu-west-1"
  "/h/eu-west-1/d/d.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/e/e.yml/eu-west-1" -> "/h/us-east-1/s/s.yml/us-east-1"
  "/h/eu-west-1/s/s.yml/eu-west-1" -> "/h/us-east-1/h/h.yml/us-east-1"
  "/h/eu-west-1/g/g.yml/eu-west-1"
  "/h/eu-west-1/h/h.yml/eu-west-1" -> "/h/eu-west-1/l/l.yml/eu-west-1"
  "/h/eu-west-1/h/h.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/i/i.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/i/i.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/i/i.yml/eu-west-1" -> "/h/us-east-1/i/i.yml/us-east-1"
  "/h/eu-west-1/i/i.yml/eu-west-1" -> "/h/eu-west-1/r/r.yml/eu-west-1"
  "/h/eu-west-1/i/i.yml/eu-west-1" -> "/h/eu-west-1/k/k.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/h/h.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/k/k.yml/eu-west-1"
  "/h/eu-west-1/k/k.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/k/k.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/l/l.yml/eu-west-1"
  "/h/eu-west-1/m/m.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/m/m.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/m/m.yml/eu-west-1" -> "/h/eu-west-1/k/k.yml/eu-west-1"
  "/h/eu-west-1/n/n.yml/eu-west-1" -> "/h/eu-west-1/l/l.yml/eu-west-1"
  "/h/eu-west-1/n/n.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/n/n.yml/eu-west-1" -> "/h/eu-west-1/b/b.yml/eu-west-1"
  "/h/eu-west-1/n/n.yml/eu-west-1" -> "/h/eu-west-1/i/i.yml/eu-west-1"
  "/h/eu-west-1/n/n.yml/eu-west-1" -> "/h/eu-west-1/h/h.yml/eu-west-1"
  "/h/eu-west-1/b/b.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/us-east-1/i/i.yml/us-east-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/h/h.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/b/b.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/r/r.yml/eu-west-1"
  "/h/eu-west-1/o/o.yml/eu-west-1" -> "/h/eu-west-1/k/k.yml/eu-west-1"
  "/h/eu-west-1/p/p.yml/eu-west-1" -> "/h/eu-west-1/l/l.yml/eu-west-1"
  "/h/eu-west-1/p/p.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/l/l.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/r/r.yml/eu-west-1"
  "/h/eu-west-1/j/j.yml/eu-west-1" -> "/h/eu-west-1/k/k.yml/eu-west-1"
  "/h/eu-west-1/q/q.yml/eu-west-1"
  "/h/eu-west-1/r/r.yml/eu-west-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/eu-west-1/r/r.yml/eu-west-1" -> "/h/eu-west-1/c/c.yml/eu-west-1"
  "/h/us-east-1/s/s.yml/us-east-1" -> "/h/us-east-1/h/h.yml/us-east-1"
  "/h/us-east-1/g/g.yml/us-east-1"
  "/h/us-east-1/h/h.yml/us-east-1"
  "/h/us-east-1/i/i.yml/us-east-1" -> "/h/eu-west-1/e/e.yml/eu-west-1"
  "/h/us-east-1/i/i.yml/us-east-1" -> "/h/eu-west-1/l/l.yml/eu-west-1"
}
```

**Comment by hmeltaus** [comment] 2020-10-12 17:55
That's one impressive dependency graph =) . It helped me to reproduce the problem. Let's see how to fix it.

**Closed** 2020-10-13 05:58 UTC
Labels: bug

**Comment by mfonsen** [comment] 2020-10-13 07:34
Excellent! I verified that the fix works and the application that worked with 1.5.1 works now with 2.10.1 as well. Thank you.

**Comment by hmeltaus** [comment] 2020-10-13 07:35
Cool. The logic that sorted the stacks in deployment order was flawed. The test cases were not complex enough to catch the bug but now, thanks to your feedback, the sorting works also in bigger setups.
